### Word Embedding Techniques Using Embedding Layer in Keras

In [1]:
### Libraries Used Tensorflow > 2.0  And Keras

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.15.0


In [4]:
## Tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### Sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary Size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[68, 446, 93, 65], [68, 446, 93, 207], [68, 216, 93, 454], [59, 367, 455, 285, 459], [59, 367, 455, 285, 338], [298, 68, 107, 93, 349], [356, 275, 282, 285]]


### Word Embedding Represntation


In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## Pre Padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0  68 446  93  65]
 [  0   0   0   0  68 446  93 207]
 [  0   0   0   0  68 216  93 454]
 [  0   0   0  59 367 455 285 459]
 [  0   0   0  59 367 455 285 338]
 [  0   0   0 298  68 107  93 349]
 [  0   0   0   0 356 275 282 285]]


In [12]:
## 10 Feature Dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5000 (19.53 KB)
Trainable params: 5000 (19.53 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [15]:
## The Glass Of Milk
embedded_docs[0]

array([  0,   0,   0,   0,  68, 446,  93,  65], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 156ms/step


array([[-0.03285917, -0.01071604,  0.04337063, -0.04456924,  0.023231  ,
         0.02965771,  0.02876272, -0.0335905 ,  0.02507508, -0.01797796],
       [-0.03285917, -0.01071604,  0.04337063, -0.04456924,  0.023231  ,
         0.02965771,  0.02876272, -0.0335905 ,  0.02507508, -0.01797796],
       [-0.03285917, -0.01071604,  0.04337063, -0.04456924,  0.023231  ,
         0.02965771,  0.02876272, -0.0335905 ,  0.02507508, -0.01797796],
       [-0.03285917, -0.01071604,  0.04337063, -0.04456924,  0.023231  ,
         0.02965771,  0.02876272, -0.0335905 ,  0.02507508, -0.01797796],
       [ 0.0222127 , -0.03521409,  0.03195692,  0.0416865 ,  0.02943147,
        -0.04034848,  0.02372215, -0.04441262,  0.03982383,  0.01368221],
       [ 0.04976866, -0.02734314,  0.03546312,  0.02486147, -0.01523743,
         0.02719792,  0.01175623,  0.03218348,  0.01464096, -0.04804164],
       [ 0.04746863,  0.02674795,  0.00238603,  0.02999457,  0.02496218,
        -0.04948087, -0.02326794,  0.0498547 

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 39ms/step
[[[-3.28591689e-02 -1.07160434e-02  4.33706306e-02 -4.45692427e-02
    2.32309960e-02  2.96577103e-02  2.87627243e-02 -3.35904956e-02
    2.50750817e-02 -1.79779641e-02]
  [-3.28591689e-02 -1.07160434e-02  4.33706306e-02 -4.45692427e-02
    2.32309960e-02  2.96577103e-02  2.87627243e-02 -3.35904956e-02
    2.50750817e-02 -1.79779641e-02]
  [-3.28591689e-02 -1.07160434e-02  4.33706306e-02 -4.45692427e-02
    2.32309960e-02  2.96577103e-02  2.87627243e-02 -3.35904956e-02
    2.50750817e-02 -1.79779641e-02]
  [-3.28591689e-02 -1.07160434e-02  4.33706306e-02 -4.45692427e-02
    2.32309960e-02  2.96577103e-02  2.87627243e-02 -3.35904956e-02
    2.50750817e-02 -1.79779641e-02]
  [ 2.22126953e-02 -3.52140889e-02  3.19569223e-02  4.16865014e-02
    2.94314735e-02 -4.03484814e-02  2.37221457e-02 -4.44126241e-02
    3.98238339e-02  1.36822127e-02]
  [ 4.97686602e-02 -2.73431428e-02  3.54631208e-02  2.48614661e-02
   -1.52374282e-02  2.71979235e

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0,  68, 446,  93,  65], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 19ms/step
[[-0.03285917 -0.01071604  0.04337063 -0.04456924  0.023231    0.02965771
   0.02876272 -0.0335905   0.02507508 -0.01797796]
 [-0.03285917 -0.01071604  0.04337063 -0.04456924  0.023231    0.02965771
   0.02876272 -0.0335905   0.02507508 -0.01797796]
 [-0.03285917 -0.01071604  0.04337063 -0.04456924  0.023231    0.02965771
   0.02876272 -0.0335905   0.02507508 -0.01797796]
 [-0.03285917 -0.01071604  0.04337063 -0.04456924  0.023231    0.02965771
   0.02876272 -0.0335905   0.02507508 -0.01797796]
 [ 0.0222127  -0.03521409  0.03195692  0.0416865   0.02943147 -0.04034848
   0.02372215 -0.04441262  0.03982383  0.01368221]
 [ 0.04976866 -0.02734314  0.03546312  0.02486147 -0.01523743  0.02719792
   0.01175623  0.03218348  0.01464096 -0.04804164]
 [ 0.04746863  0.02674795  0.00238603  0.02999457  0.02496218 -0.04948087
  -0.02326794  0.0498547   0.04016386 -0.00791305]
 [ 0.03008466 -0.02345058 -0.04043547  0.02634803 -0.01867909  0.03007013

In [20]:
### Assignment
